### ISSUE TITLE
BIG TODO

### ISSUE THREAD

**Issue by coco-as-co** [SylvainBoudacher/Thanatos#49]
- [ ] Revoir la modification de l'email dans les paramètres
- [ ] Système mot de passe
- [ ] Ajout maps adresse

**Front (à faire ou refaire)** 
- [ ] Les erreurs des formulaires
<img width="406" alt="image" src="https://user-images.githubusercontent.com/74983957/178464311-1cc37a21-abd1-4b9c-82a4-341f5b7fa52d.png">

- [ ] Ajoute confirmation dialogue avant de supprimer un corps lors de la déclaration de corps

- [ ] Bouton supprimer pour les media
<img width="169" alt="image" src="https://user-images.githubusercontent.com/74983957/178466775-0fbc5da4-dd4e-4675-ba7e-99c96a98db18.png">
